import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/footer/Footer";
import Sessionprovider from "@/components/SessionProvider";

export const metadata: Metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session: any;
}>) {
  return (
    <html lang="en">
      <body>
        <Sessionprovider session={session}>
          <Navbar />
          {children}
          <Footer />
        </Sessionprovider>
      </body>
    </html>
  );
}
